'use client';

import Link from 'next/link';
function PrivacyContent() {
    return (
       <>
        <div className='row'>
            <div className='col-lg-12 pt-lg-4 pt-sm-43 pt-3 pb-3'>
                <h1>Privacy Policy</h1>
                <p><strong>Definitions</strong></p>
                <p>Flex Pass is committed to protecting your privacy and governs the Privacy Terms of our website, located at https://www.myFlexPass.com/privacypolicy. This Privacy Policy explains how your personal information is collected, used, and disclosed by our Company. By accessing or using our Service, you announce that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                </p>
                <ul>
                    <li><strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from such data. Personal Data is any information that directly, indirectly, or in connection with other information allows for the identification of a natural person.</li>
                    <li>
                        <strong>Cookies:</strong> Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                    <li>
                        <strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                    </li>
                    <li>
                        <strong> Data Subject:</strong> Data Subject is any living individual who is the subject of Personal Data.
                    </li>
                    <li><strong>User:</strong> The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
                </ul>
                <h5>What Information Do We Collect?</h5>
                <p>We collect several types of information for various purposes to provide and improve our Service to you.</p>
                <h5>Types of Data Collected</h5>
                <h5>• Personal Data</h5>
                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (Personal Data). It means - Email address, first and last name, date of birth, address, city, state/Country, Postcode, Phone, Date of birth.</p>
                <h5>• Credit/Debit Card Information</h5>
                <p>We do not store this information. We leverage Stripe, our payment vendor, for collection and storage of said information.</p>
                <h5>• Usage Data</h5>
                <p>We may also collect information on how the Service is accessed and used (Usage Data). This Usage Data may include information such as your computer’s Internet Protocol address (IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <h5>• Tracking & Cookies Data</h5>
                <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
                <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
                <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                <h5>How do we use the information we collect?</h5>
                <p>Any of the information we collect from you may be used in one of the following ways:</p>
                <p>• To personalize your experience (your information helps us to better respond to your individual needs)</p>
                <ul>
                    <li><p >
                        <font color="#000000"><font face="Lato, sans-serif"><font size="2">To
                            improve our Service (we continually strive to improve </font></font></font><font face="Lato, sans-serif"><font size="2">our
                                application offerings based on the information and feedback we
                                receive from you) </font></font>
                    </p></li>
                    <li><p >
                        <font face="Lato, sans-serif"><font size="2">To
                            process transactions </font></font>
                    </p></li>
                    <li><p>
                        <font face="Lato, sans-serif"><font size="2">To
                            send periodic emails </font></font>
                    </p></li>
                    <li><p>
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >To
                            notify you about changes to our Service </font></font></font>
                    </p></li>
                    <li><p >
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >To
                            gather analysis or valuable information so that we can improve our
                            services </font></font></font>
                    </p></li>
                    <li><p >
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >To
                            monitor the usage of our Service </font></font></font>
                    </p></li>
                    <li><p >
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >To
                            detect, prevent and address technical issues </font></font></font>
                    </p></li>
                    <li><p >
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >To
                            provide you with news, special offers and general information about
                            other goods, services and events which we offer that are similar to
                            those that you have already purchased or enquired about unless you
                            have opted not to receive such information </font></font></font>
                    </p></li>
                </ul>
                <h5>How do we use your email address? </h5>
                <p>By
                    submitting your email address, you agree to receive emails from us.
                    You can cancel your participation in any of these email lists at any
                    time by clicking on the opt-out link or other unsubscribe option that
                    is included in the respective email. We only send emails to people
                    who have authorized us to contact them, either directly, or through a
                    third party. We do not send unsolicited commercial emails, because we
                    hate spam as much as you do. </p>
                <p>Email
                    addresses submitted only through the order processing page will be
                    used for the sole purpose of sending you information and updates
                    pertaining to your order. If, however, you have provided the same
                    email to us through another method, we may use it for any of the
                    purposes stated in this Policy. Note: If at any time you would like
                    to unsubscribe from receiving future emails, we include detailed
                    unsubscribe instructions at the bottom of each email. </p>
                <h5>How long do we keep your
                    information? </h5>
                <p>We
                    will retain the information we collect from you for a period of two
                    (2) years, or until you are an active user of the services we
                    provide. After the expiry of this period, we undertake to delete any
                    information we have collected from you. </p>
                <h5>Disclosure of data</h5>
                <p>We will retain your Personal Data for a period of two (2) years. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p>We
                    will also retain Usage Data for internal analysis purposes. Usage
                    Data is generally retained for a shorter period of time, except when
                    this data is used to strengthen the security or to improve the
                    functionality of our Service, or we are legally obligated to retain
                    this data for longer time periods. </p>
                <ul>
                    <li><p >
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" ><b>Business
                            Transaction. </b></font></font></font><font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >If
                                we are involved in a merger, acquisition or asset sale, your
                                Personal Data may be transferred. We will provide notice before your
                                Personal Data is transferred and becomes subject to a different
                                Privacy Policy. </font></font></font>
                    </p></li>
                    <li><p >
                        <font color="#1e2328"><font face="Lato, sans-serif"><font size="2" ><b>Disclosure
                            for Law Enforcement. </b></font></font></font><font color="#1e2328"><font face="Lato, sans-serif"><font size="2" >Under
                                certain circumstances, we may be required to disclose your Personal
                                Data if required to do so by law or in response to valid requests by
                                public authorities (e.g., a court or a government agency). </font></font></font>
                    </p></li>
                </ul>
                <h5>How do we protect your information? </h5>
                <p>We
                    implement a variety of security measures to maintain the safety of
                    your personal information when you place an order or enter, submit,
                    or access your personal information. </p>
                <h5>Your consent </h5>
                <p>By
                    using our Website, registering an account, accessing our services,
                    you consent to this Privacy Policy Term. </p>
                <p>This Privacy Policy applies only to our Services.</p>
                <h5>Information
                    collected automatically </h5>
                <p>feature
                    you requested. “Cookies” are identifiers we transfer to your
                    browser or device that allow us to recognize your browser or device
                    and tell us how and when pages and features in our Services are
                    visited and by how many people. You may be able to change the
                    preferences on your browser or device to prevent or limit your
                    device’s acceptance of cookies, but this may prevent you from
                    taking advantage of some of our features. Our advertising partners
                    may also transmit cookies to your browser or device, when you click
                    on ads that appear on the Services. Also, if you click on a link to a
                    third-party website or service, such third party may also transmit
                    cookies to you. Again, this Privacy Policy does not cover the use of
                    cookies by any third parties, and we aren’t responsible for their
                    privacy policies and practices. Please be aware that cookies placed
                    by third parties may continue to track your activities online even
                    after you have left our Services, and those third-parties may not
                    honor “Do Not Track” requests you have set using your browser or
                    device. </p>
                <p>We
                    may use this data to customize content for you that we think you
                    might like, based on your usage patterns. We may also use it to
                    improve the Services—for example, this data can tell us how often
                    users use a particular feature of the Services, and we can use that
                    knowledge to make the Services interesting to as many users as
                    possible. </p>
                <h5>Security of Your Information </h5>
                <p>Your
                    account is protected by a password for your privacy and security. You
                    must prevent unauthorized access to your account and Personal
                    Information by selecting and protecting your password appropriately
                    and limiting access to your computer or device and browser by signing
                    off after you have finished accessing your account. </p>
                <p>We
                    endeavor to protect the privacy of your account and other Personal
                    Information we hold in our records, but unfortunately, we cannot
                    guarantee complete security. Unauthorized entry or use, hardware or
                    software failure, and other factors, may compromise the security of
                    user information at any time. </p>
                <h5>Information retention and deletion </h5>
                <p>Through
                    your account settings, you may access, and, in some cases, edit or
                    delete the following information you’ve provided to us: </p>
                <p >
                    <font face="Lato, sans-serif"><font size="2" >-
                        name<br />
                        - password<br />
                        - email address<br />
                        - credit card
                        information </font></font>
                </p>
                <p>Please
                    note that, although you can delete your existing credit card
                    information on your account, we may save a unique-identification
                    “fingerprint” for that credit card solely for our internal use to
                    identify that card as being associated with your account. </p>
                <p>The
                    information you can view, update, and delete may change as the
                    Services change. If you have any questions about viewing or updating
                    information, we have on file about you. Please contact us at <Link href={''}>info@myFlexPass.com</Link></p>
                <h5>Your choices</h5>
                <p>You
                    can always opt not to disclose information to us, but keep in mind
                    some information may be needed to register with us or to take
                    advantage of some of our features.</p>
                <h5>For California users</h5>
                <p>Personal
                    Data collected for the following purposes and using the following
                    services: </p>
                <h5>Access to third-party accounts </h5>
                <p><strong>Access to third-party accounts </strong></p>
                <p>Permissions: About Me; Contact email; Email; Photos</p>
                <p><strong>Stripe
                    account access</strong></p>
                <p>Personal
                    Data: various types of Data as specified in the privacy policy of the
                    service </p>
                <h5>Analytics</h5>
                <p><strong>Google
                    Analytics, Analytics collected directly and Facebook Ads conversion
                    tracking (Facebook pixel)  </strong></p>
                <p>Personal
                    Data: Cookies; Usage Data </p>
                <p><strong>Facebook
                    Analytics for Apps</strong></p>
                <p>Personal
                    Data: Usage Data; various types of Data as specified in the privacy
                    policy of the service </p>
                <h5>Contacting the User</h5>
                <p><strong>Mailing
                    list or newsletter </strong></p>
                <p>Personal
                    Data: city; country; email address; first name; last name </p>
                <p><strong>Phone
                    contact </strong></p>
                <p>Personal
                    Data: phone number </p>
                <h5>Device permissions for Personal Data
                    access </h5>
                <p><strong>Device
                    permissions for Personal Data access </strong></p>
                <p>Personal
                    Data: Approximate location permission (continuous); Call permission;
                    Camera permission; Contacts permission; Phone permission; SMS
                    permission; Social media accounts permission; Storage permission. </p>
                <p><strong>Handling payments • Stripe</strong></p>
                <p>Personal Data: various types of Data as specified in the privacy policy of the service</p>
                <p><strong>Location-based interactions • Geolocation</strong></p>
                <p>Personal Data: geographic position</p>
                <p>Personal Data: Cookies; Usage Data</p>
                <h5>The Service is not directed to children under the age of 18</h5>
                <p><strong>Access to third-party accounts </strong></p>
                <p>Users
                    declare themselves to be adult according to their applicable
                    legislation. Minors may use this application only with the assistance
                    of a parent or guardian. Under no circumstance, persons under the age
                    of 18 may use this service. </p>
                <h5>Unique device identification</h5>
                <p>This application may track Users by storing a unique identifier of their device, for analytics purposes or for storing Users preferences.</p>
                <p>Flex Pass may process your Personal Data because:</p>
                <ul>
                    <li><p >
                        <font face="Lato, sans-serif"><font size="2" >We
                            need to perform a contract with you </font></font>
                    </p></li>
                    <li><p >
                        <font face="Lato, sans-serif"><font size="2" >You
                            have given us permission to do so </font></font>
                    </p></li>
                    <li><p >
                        <font face="Lato, sans-serif"><font size="2">The
                            processing is in our legitimate interests, and it’s not overridden
                            by your rights </font></font>
                    </p></li>
                    <li><p >
                        <font face="Lato, sans-serif"><font size="2">For
                            payment processing purposes </font></font>
                    </p></li>
                    <li><p >
                        <font face="Lato, sans-serif"><font size="2">To
                            comply with the law </font></font>
                    </p></li>
                </ul>
                <h5>Governing Law</h5>
                <p>This
                    Privacy Policy and the use of the Website/App are governed by the
                    laws of California. The parties undertake to first try to resolve the
                    dispute with by negotiation. If the parties fail to reach an amicable
                    resolution through negotiation, Flex Pass agrees to submit the
                    dispute to the competent jurisdiction of the State and federal courts
                    in San Jose. </p>
                <h5>Data
                    Protection Officer </h5>
                <p>We
                    have appointed a Data Protection Officer (“DPO”) who is
                    responsible for overseeing questions about this privacy notice. If
                    you have any questions about this privacy notice, including any
                    requests to exercise your legal rights, please contacts Data
                    Protection Officer, at </p>
                <h5>Changes to this Privacy Policy </h5>
                <p>We
                    may update our Privacy Policy from time to time. We will notify you
                    of any changes by posting the new Privacy Policy on this app.</p>
                <p>We
                    will let you know via email and/or a prominent notice on our Service,
                    prior to the change becoming effective and update the `effective date` at the top of this Privacy Policy. </p>
                <p>You
                    are advised to review this Privacy Policy periodically for any
                    changes. Changes to this Privacy Policy are effective when they are
                    posted on this page. </p>
                <h5>Contact Us</h5>
                <p>If you have any questions about this Privacy Policy, don’t hesitate to contact us. e-mail: <Link href={''}>info@myFlexPass.com</Link>
                </p>
            </div>
        </div>
       </>
    )
}

export default PrivacyContent